sudo: required

services:
  - docker

language: node_js

node_js:
  - "4.1"
  
before_install:
  - echo "node version $(node -v) running"
  - echo "npm version $(npm -v) running"
  
install:
  - bundle install
  - npm install
  
script:
  - gulp build
  - docker build -t site .
  
after_success:
- docker tag site connecter/site:travis
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push connecter/site:travis